"""Replaceable record and blob storage boundaries."""
from pathlib import Path
from typing import BinaryIO, Iterable, Protocol

from optimization_framework.contracts.experiments import ArtifactReference


class Repository(Protocol):
    def get(self, record_id: str, kind: str | None = None) -> dict: ...
    def get_entry(self, record_id: str) -> dict: ...
    def list(self, kind: str, campaign_id: str | None = None) -> list[dict]: ...
    def put(self, kind: str, record: dict, event: str | None = None) -> dict: ...
    def put_many(self, entries: Iterable[tuple[str, dict, str | None]]) -> None: ...
    def put_immutable(self, kind: str, record: dict, event: str | None = None) -> dict: ...
    def transaction(self): ...
    def record_position(self, record_id: str) -> int: ...
    def events(self, campaign_id: str | None = None, after: int = 0, limit: int = 200) -> list[dict]: ...
    def recent_events(self, campaign_id: str | None = None, limit: int = 200) -> list[dict]: ...


class ArtifactStore(Protocol):
    def put_stream(self, source: BinaryIO, *, media_type: str = "application/octet-stream") -> ArtifactReference: ...
    def open(self, reference: ArtifactReference) -> BinaryIO: ...
    def verify(self, reference: ArtifactReference) -> None: ...
