"""The synchronous v1 optimizer lifecycle; one outstanding ordered batch."""
from typing import Protocol

from .problems import Observation, Proposal


class Optimizer(Protocol):
    def initialize(self, problem_descriptor: dict, parameters: dict, seed: int, declared_assets: list[dict]) -> None: ...
    def propose(self, max_candidates: int = 1) -> list[Proposal]: ...
    def observe(self, observations: list[Observation]) -> None: ...
    def checkpoint(self) -> dict: ...
    def restore(self, manifest: dict) -> None: ...
    def inspect(self) -> dict: ...
    def export_artifacts(self) -> list[dict]: ...
